CONST = "Hello, my name is Inigo Montoya"
m = (CONST[7:8])
m = str(m.upper())
print(CONST[0:5])
print(CONST[7:14])
print(CONST[0:1], end="")
print(CONST[3:5], end="")
print(CONST[6:7], end="")
print(CONST[8:9], end="")
print(CONST[10:11], end="")
print(CONST[12:13], end="")
print(CONST[6:7], end="")
print(CONST[16:17], end="")
print(CONST[2:3], end="")
print(CONST[15:16], end="")
print(CONST[4:5], end="")
print(m, end="")
print(CONST[10:11], end="")
print(CONST[4:5], end="")
print(CONST[11:12])
print(CONST[3:5], end="")
print(CONST[6:7], end="")
